### ISSUE TITLE
update to Angular 4

### ISSUE THREAD

**Issue by megalucio** [gnucoop/material2-extra#6]
#### feature request

Upgrade to Angular 4

#### What is the expected behavior?

For the component to work in Angular 4

#### What is the current behavior?

Getting ERROR Error: Uncaught (in promise): TypeError: instance[output.propName].subscribe is not a function
TypeError: instance[output.propName].subscribe is not a function

#### What are the steps to reproduce?

Just introduce 

<md-calendar (change)="onPeriodChange($event)"></md-calendar>

inside an html in your Angular 4 project

#### Which versions of Angular, Material, OS, browsers are affected?

Angular 4

#### Is there anything else we should know?

This should be easily fixed by replacing
`const VALUE_ACCESSOR = {
    NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => MyComponent),
    multi: true
};`

with 

`const VALUE_ACCESSOR = new Provider(NG_VALUE_ACCESSOR, {
    useExisting: forwardRef(() => MyComponent),
    multi: true
});`

as explained [here](https://github.com/angular/angular/issues/8519)

**Comment by trik** [comment]
updated to angular 4.1.3 and material 2 beta 8
